CREATE OR REPLACE FUNCTION CalculateAge(p_DOB IN DATE)
RETURN NUMBER IS
    v_Age NUMBER;
BEGIN
    v_Age := FLOOR(MONTHS_BETWEEN(SYSDATE, p_DOB) / 12);
    RETURN v_Age;
END;

SELECT CalculateAge(TO_DATE('1990-07-20', 'YYYY-MM-DD')) AS Age FROM dual;
